# Generated by Django 3.2.6 on 2021-12-31 14:12

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.IntegerField(unique=True, verbose_name='S.No.')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Event Name')),
                ('position', models.CharField(default=None, max_length=255, verbose_name='Event Data & Time')),
            ],
            options={
                'verbose_name_plural': 'Advisory Committee',
            },
        ),
        migrations.CreateModel(
            name='ActivityCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=255, verbose_name=' Year ')),
                ('pdf1', models.FileField(null=True, upload_to=core.models.file_path15, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF File')),
            ],
            options={
                'verbose_name_plural': 'Activity Calendar',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=core.models.file_path16, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF File')),
            ],
            options={
                'verbose_name_plural': 'Assets Created',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=255, verbose_name=' Year ')),
                ('description', models.TextField(default=None, max_length=500, null=True, verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to=core.models.file_path9, verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Awards & Achievements',
            },
        ),
        migrations.CreateModel(
            name='BDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=255, verbose_name='Event Date ')),
                ('donated_to', models.CharField(default=None, max_length=255, verbose_name=' Donated to ')),
                ('count', models.IntegerField(unique=True, verbose_name='Units')),
                ('photo', models.ImageField(null=True, upload_to=core.models.file_path12, verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Blood Donation Camp (BDC)',
            },
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=255, verbose_name='Event Date ')),
                ('description', models.TextField(default=None, max_length=500, null=True, verbose_name='Description')),
                ('video', models.URLField(default=None, max_length=500, null=True, verbose_name='Video URL')),
            ],
            options={
                'verbose_name_plural': 'Camp Organised',
            },
        ),
        migrations.CreateModel(
            name='DL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Scheme Title ')),
                ('image1', models.ImageField(null=True, upload_to=core.models.file_path5, verbose_name='Image 1')),
                ('date1', models.CharField(default=None, max_length=255, verbose_name='Date')),
                ('image2', models.ImageField(null=True, upload_to=core.models.file_path5, verbose_name='Image 2')),
                ('date2', models.CharField(default=None, max_length=255, verbose_name='Date')),
                ('image3', models.ImageField(null=True, upload_to=core.models.file_path5, verbose_name='Image 3')),
                ('date3', models.CharField(default=None, max_length=255, verbose_name='Date')),
                ('image4', models.ImageField(null=True, upload_to=core.models.file_path5, verbose_name='Image 4')),
                ('date4', models.CharField(default=None, max_length=255, verbose_name='Date')),
                ('video', models.URLField(default=None, max_length=500, null=True, verbose_name='Video URL')),
                ('place', models.CharField(default=None, max_length=255, verbose_name='Place')),
            ],
            options={
                'verbose_name_plural': 'Digital Literacy',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.file_path1, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg'])], verbose_name='Home Slider')),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='NLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=255, verbose_name=' Year ')),
                ('image1', models.ImageField(null=True, upload_to=core.models.file_path6, verbose_name='Image 1')),
                ('image2', models.ImageField(null=True, upload_to=core.models.file_path6, verbose_name='Image 2')),
                ('image3', models.ImageField(null=True, upload_to=core.models.file_path6, verbose_name='Image 3')),
                ('image4', models.ImageField(null=True, upload_to=core.models.file_path6, verbose_name='Image 4')),
                ('place', models.CharField(default=None, max_length=255, verbose_name='Place')),
            ],
            options={
                'verbose_name_plural': 'National Literacy Mission',
            },
        ),
        migrations.CreateModel(
            name='PMY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Scheme Title ')),
                ('Objective', models.TextField(default=None, max_length=500, null=True, verbose_name='Objective')),
                ('link', models.URLField(default=None, max_length=500, null=True, verbose_name='Read More Link')),
                ('image', models.ImageField(null=True, upload_to=core.models.file_path4, verbose_name='Scheme Image')),
            ],
            options={
                'verbose_name_plural': 'Pradhan Mantri Yojana (PMY)',
            },
        ),
        migrations.CreateModel(
            name='POs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Event Name')),
                ('position', models.CharField(default=None, max_length=255, verbose_name='Event Data & Time')),
                ('photo', models.ImageField(null=True, upload_to=core.models.file_path3, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg'])], verbose_name='Photo')),
            ],
            options={
                'verbose_name_plural': 'Programme Officers',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=255, verbose_name=' type ')),
                ('year', models.CharField(default=None, max_length=255, verbose_name=' Year ')),
                ('file', models.FileField(null=True, upload_to=core.models.file_path14, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF File')),
            ],
            options={
                'verbose_name_plural': 'Reports & Magazines',
            },
        ),
        migrations.CreateModel(
            name='Sapling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default=None, max_length=255, verbose_name='Event Name ')),
                ('About', models.TextField(default=None, max_length=500, null=True, verbose_name='Event Description')),
                ('count', models.CharField(default=None, max_length=255, verbose_name=' Year ')),
                ('image1', models.ImageField(null=True, upload_to=core.models.file_path11, verbose_name='Image 1')),
            ],
            options={
                'verbose_name_plural': 'Sapling Plantation',
            },
        ),
        migrations.CreateModel(
            name='SBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=255, verbose_name=' Year ')),
                ('image1', models.ImageField(null=True, upload_to=core.models.file_path7, verbose_name='Image 1')),
                ('image2', models.ImageField(null=True, upload_to=core.models.file_path7, verbose_name='Image 2')),
                ('image3', models.ImageField(null=True, upload_to=core.models.file_path7, verbose_name='Image 3')),
                ('image4', models.ImageField(null=True, upload_to=core.models.file_path7, verbose_name='Image 4')),
                ('place', models.CharField(default=None, max_length=255, verbose_name='Place')),
                ('video', models.URLField(default=None, max_length=500, null=True, verbose_name='Video URL')),
            ],
            options={
                'verbose_name_plural': 'Swachh Bharath Mission',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=255, verbose_name='Event Date ')),
                ('description', models.TextField(default=None, max_length=500, null=True, verbose_name='Description')),
                ('photo', models.ImageField(null=True, upload_to=core.models.file_path13, verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Seminars & Conferences',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.file_path2, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg'])], verbose_name='Services Slider')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='UBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default=None, max_length=255, verbose_name='Event Name ')),
                ('date', models.CharField(default=None, max_length=255, verbose_name=' Year ')),
                ('description', models.TextField(default=None, max_length=500, null=True, verbose_name='Description')),
                ('image1', models.ImageField(null=True, upload_to=core.models.file_path8, verbose_name='Image 1')),
                ('image2', models.ImageField(null=True, upload_to=core.models.file_path8, verbose_name='Image 2')),
            ],
            options={
                'verbose_name_plural': 'Unnat Bharat Abhiyan(UBA)',
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default=None, max_length=255, verbose_name='Event Name')),
                ('date', models.CharField(default=None, max_length=255, verbose_name='Event Data & Time')),
            ],
            options={
                'verbose_name_plural': 'Upcoming Events',
            },
        ),
        migrations.CreateModel(
            name='VT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name ')),
                ('skill', models.CharField(default=None, max_length=255, verbose_name='Skill ')),
                ('file', models.FileField(null=True, upload_to=core.models.file_path10, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'jpg'])], verbose_name='Video or Image')),
                ('image1', models.ImageField(null=True, upload_to=core.models.file_path10, verbose_name='Image 1')),
                ('image2', models.ImageField(null=True, upload_to=core.models.file_path10, verbose_name='Image 2')),
            ],
            options={
                'verbose_name_plural': 'Volunteers Talent',
            },
        ),
    ]
