# Generated by Django 3.2.6 on 2022-01-01 11:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ac_activitycalendar_assets_awards_bdc_camp_dl_home_nlm_pmy_pos_reports_sapling_sbm_seminar_services_'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapling',
            name='year',
            field=models.CharField(default=None, max_length=255, verbose_name=' Year '),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.file_path1, verbose_name='Home Slider'),
        ),
        migrations.AlterField(
            model_name='sapling',
            name='count',
            field=models.CharField(default=None, max_length=255, verbose_name=' Sampling Count '),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.file_path2, verbose_name='Services Slider'),
        ),
    ]
