# Generated by Django 3.2.6 on 2022-01-10 16:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220101_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default=None, max_length=255, verbose_name='Event Name ')),
                ('date', models.CharField(default=None, max_length=255, verbose_name=' Date & Time ')),
                ('description', models.TextField(default=None, max_length=500, null=True, verbose_name='Description')),
                ('image1', models.ImageField(null=True, upload_to=core.models.file_path18, verbose_name='Image 1')),
                ('image2', models.ImageField(null=True, upload_to=core.models.file_path18, verbose_name='Image 2')),
                ('image3', models.ImageField(null=True, upload_to=core.models.file_path18, verbose_name='Image 3')),
                ('image4', models.ImageField(null=True, upload_to=core.models.file_path18, verbose_name='Image 4')),
                ('video', models.URLField(default=None, max_length=500, null=True, verbose_name='Youtube URL')),
            ],
            options={
                'verbose_name_plural': 'Events Organised (Others)',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.file_path17, verbose_name='Structure Image(Replace this only for update)')),
            ],
            options={
                'verbose_name_plural': 'NSS Structure',
            },
        ),
        migrations.DeleteModel(
            name='DL',
        ),
        migrations.DeleteModel(
            name='SBM',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services<built-in function id>'},
        ),
        migrations.AddField(
            model_name='nlm',
            name='event',
            field=models.CharField(default=None, max_length=255, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='nlm',
            name='video',
            field=models.URLField(default=None, max_length=500, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='uba',
            name='image3',
            field=models.ImageField(null=True, upload_to=core.models.file_path8, verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='uba',
            name='image4',
            field=models.ImageField(null=True, upload_to=core.models.file_path8, verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='uba',
            name='place',
            field=models.CharField(default=None, max_length=255, verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='uba',
            name='video',
            field=models.URLField(default=None, max_length=500, null=True, verbose_name='Youtube URL'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='position',
            field=models.CharField(default=None, max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='nlm',
            name='date',
            field=models.CharField(default=None, max_length=255, verbose_name='Date & Year '),
        ),
        migrations.AlterField(
            model_name='pos',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='position',
            field=models.CharField(default=None, max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='type',
            field=models.CharField(choices=[('Report', 'Report'), ('Magazine', 'Magazine')], default=None, max_length=255, verbose_name=' type '),
        ),
        migrations.AlterField(
            model_name='vt',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.file_path10, verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='vt',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.file_path10, verbose_name='Image 2'),
        ),
    ]
